# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
tab_spaces = 3
max_width = 120
fn_call_width = 110
use_small_heuristics = "Max"
single_line_if_else_max_width = 110
single_line_let_else_max_width = 110
struct_lit_width = 110
struct_variant_width = 110
short_array_element_width_threshold = 100
fn_single_line = true
fn_params_layout = "Compressed"
match_arm_blocks = false
newline_style = "Unix"
overflow_delimited_expr = true
reorder_modules = false
trailing_semicolon = false
unstable_features = true
format_macro_bodies = false
match_block_trailing_comma = true
merge_derives = false
style_edition = "2024"
use_field_init_shorthand = true
where_single_line = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
