//! scratchpad.rs is generated by running `cargo test`.
//! Used to test the output of Ascent macros.

#![allow(unused_imports)]
use std::{clone, cmp::max, rc::Rc};
use std::ops::Deref;
use std::hash::Hash;
use std::fmt::Debug;

fn main() {
    _test();
}

#[warn(warnings)]
#[allow(unused_imports)]
#[allow(dead_code)]
#[allow(redundant_semicolons)]
fn _test() {
   use ascent::aggregators::*;
   use ascent::lattice::set::Set;
   use ascent::Dual;

   use ascent::rel as custom_ds;
   todo!("here");
   ;
}