[package]
name = "ascent_base"
version.workspace = true
edition = "2021"
authors = ["Arash Sahebolamri"]
repository = "https://github.com/s-arash/ascent"
license = "MIT"
description = "support library for the ascent package"

[dependencies]
pastey = "0.1.1"
